%实现锯齿形灰度拉伸
ImageInRGB=imread('G:\大三下\数字图像处理与机器视觉\code_matlab\2\apple2.png');
ImageIn=rgb2gray(ImageInRGB);
%将原来的图像分为五个段
step1=50;
step2=100;
step3=150;
step4=200;
step5=255;
%每一段映射到10-220
MinShow=10;
MaxShow=220;
%得到逻辑值矩阵,再按位相与
ImageShow1=ImageIn.*uint8(ImageIn<step1);
ImageShow1=(MaxShow-MinShow)/(step1-0)*(ImageShow1-0)+MinShow;
ImageShow2=ImageIn.*uint8((ImageIn>step1)&(ImageIn<step2));
ImageShow2=(MaxShow-MinShow)/(step2-step1)*(ImageShow2-step1)+MinShow;
ImageShow3=ImageIn.*uint8((ImageIn>step2)&(ImageIn<step3));
ImageShow3=(MaxShow-MinShow)/(step3-step2)*(ImageShow3-step2)+MinShow;
ImageShow4=ImageIn.*uint8((ImageIn>step3)&(ImageIn<step2));
ImageShow4=(MaxShow-MinShow)/(step4-step3)*(ImageShow4-step3)+MinShow;
ImageShow5=ImageIn.*uint8((ImageIn>step4)&(ImageIn<step3));
ImageShow5=(MaxShow-MinShow)/(step5-step4)*(ImageShow5-step4)+MinShow;
ImageShow=ImageShow1+ImageShow2+ImageShow3+ImageShow4+ImageShow5;
subplot(1,2,1);
imshow(ImageIn);
title('原图像');
subplot(1,2,2);
imshow(ImageShow);
title('锯齿形灰度拉伸');

